# Generated by Django 4.0.4 on 2022-05-13 01:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(db_index=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Questao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questao', models.CharField(max_length=1000)),
                ('correta', models.IntegerField()),
                ('opcao_um', models.CharField(max_length=100)),
                ('opcao_dois', models.CharField(max_length=100)),
                ('opcao_tres', models.CharField(max_length=100)),
                ('opcao_quatro', models.CharField(max_length=100)),
                ('opcao_cinco', models.CharField(max_length=100)),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questoes.materia')),
            ],
        ),
    ]
