# Generated by Django 4.0.4 on 2022-05-10 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questoes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='materia',
            options={'ordering': ('nome_materia',), 'verbose_name': 'matéria', 'verbose_name_plural': 'matérias'},
        ),
        migrations.AlterModelOptions(
            name='questao',
            options={'ordering': ('questao',), 'verbose_name': 'questão', 'verbose_name_plural': 'questões'},
        ),
        migrations.RenameField(
            model_name='materia',
            old_name='mome_materia',
            new_name='nome_materia',
        ),
        migrations.AlterField(
            model_name='questao',
            name='resposta',
            field=models.IntegerField(),
        ),
    ]
