# Generated by Django 4.0.4 on 2022-05-13 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questoes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questao',
            name='correta',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
