# Generated by Django 4.0.4 on 2022-05-10 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questoes', '0002_alter_materia_options_alter_questao_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='materia',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=250, unique=True, verbose_name='Slug'),
        ),
    ]
