# Generated by Django 4.0.4 on 2022-05-13 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questoes', '0002_alter_questao_correta'),
    ]

    operations = [
        migrations.AddField(
            model_name='questao',
            name='valor',
            field=models.IntegerField(default=5),
        ),
    ]
