# Generated by Django 4.0.4 on 2022-05-11 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questoes', '0005_alter_questao_questao'),
    ]

    operations = [
        migrations.AddField(
            model_name='questao',
            name='marks',
            field=models.IntegerField(default=5),
        ),
    ]
