# Generated by Django 4.0.4 on 2022-05-11 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questoes', '0007_placar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materia',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='questao',
            name='slug',
        ),
    ]
