# Generated by Django 4.0.5 on 2022-06-30 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_alter_question_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='descricao',
            field=models.TextField(blank=True),
        ),
    ]
